language: php

php:
  - 7.3
  - 7.2

before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

addons:
  mariadb: '10.2'

cache:
  directories:
    - vendor
